services:
  - type: web
    name: flask-email-sender
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
